server:
  port : 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
#          filters:
#            - AuthenticationFilter

        - id: protected-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter
            - RemoveRequestHeader=Cookie
            - RemoveRequestHeader=Set-Cookie

#application:
#  name: SWIGGY-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/